#!/bin/sh
# Build the 32-bit harness tools into build/harness/:
#   tvh.exe       drives the original CGRM_EN.DLL engine (the oracle)
#   tvh_hook.exe  same, with every decompiled function from src/ hooked in
#
# Uses the x86_64 mingw toolchain in freestanding -m32 mode: no 32-bit
# libc/libgcc is installed, so we link against msvcrt.dll/kernel32.dll import
# libraries generated by dlltool from harness/rt/*.def.
set -e
cd "$(dirname "$0")/.."
OUT=build/harness
GEN=build/gen
HOOK=build/hook
mkdir -p "$OUT" "$GEN" "$HOOK/obj"
CFLAGS="-m32 -std=gnu11 -O2 -g -Wall -Wno-unused-function -D__USE_MINGW_ANSI_STDIO=0 \
  -fno-asynchronous-unwind-tables -fno-stack-protector -fno-builtin-printf -fwrapv -fno-strict-aliasing \
  -Iharness"

for lib in kernel32 msvcrt user32; do
  if [ ! -f "$OUT/lib$lib.a" ] || [ "harness/rt/$lib.def" -nt "$OUT/lib$lib.a" ]; then
    dlltool -m i386 --as-flags=--32 -k -d "harness/rt/$lib.def" -l "$OUT/lib$lib.a"
  fi
done

RT=""
for src in harness/rt/start.c harness/rt/libgcc32.c harness/rt/chkstk.S \
           harness/peload.c harness/sandbox.c harness/coverage.c; do
  obj="$OUT/$(basename "$src" | sed 's/\.[cS]$/.o/')"
  gcc $CFLAGS -c "$src" -o "$obj"
  RT="$RT $obj"
done

link() { # link <exe> <extra ld args...>
  exe=$1; shift
  # Fixed base, no relocations: hook code calls/jumps straight to absolute
  # addresses inside the DLL, which must not shift if the exe were rebased.
  ld -m i386pe --subsystem console -e _mainCRTStartup@0 --stack 0x800000 \
    --disable-dynamicbase --disable-reloc-section \
    -o "$exe" "$@" $RT "$OUT/libmsvcrt.a" "$OUT/libkernel32.a" "$OUT/libuser32.a"
}

# --- oracle -----------------------------------------------------------------
gcc $CFLAGS -c harness/tvh.c -o "$OUT/tvh.o"
link "$OUT/tvh.exe" "$OUT/tvh.o"
echo "built $OUT/tvh.exe"

# --- hook build ---------------------------------------------------------------
for f in src/*.fields; do
  python tools/gen_struct.py "$f" "$GEN/$(basename "$f" .fields)_struct.h"
done
HOOK_OBJS=""
for src in $(find src -name '*.c' -not -path 'src/data/*' -not -path 'src/port/*' | sort); do
  obj="$HOOK/obj/$(echo "$src" | sed 's|^src/||; s|/|_|g; s|\.c$|.o|')"
  gcc $CFLAGS -DTV_HOOK_BUILD -Isrc -I"$GEN" -c "$src" -o "$obj"
  HOOK_OBJS="$HOOK_OBJS $obj"
done
python tools/gen_hookmap.py src "$HOOK/hooks_gen.c" "$HOOK/defsyms.txt" $HOOK_OBJS
gcc $CFLAGS -c "$HOOK/hooks_gen.c" -o "$HOOK/hooks_gen.o"
gcc $CFLAGS -c harness/hooks.c -o "$HOOK/hooks.o"
gcc $CFLAGS -DTV_HOOK_BUILD -Isrc -I"$GEN" -c harness/unit.c -o "$HOOK/unit.o"
gcc $CFLAGS -DTV_WITH_HOOKS -c harness/tvh.c -o "$HOOK/tvh_hook.o"
link "$OUT/tvh_hook.exe" @"$HOOK/defsyms.txt" "$HOOK/tvh_hook.o" "$HOOK/hooks.o" \
  "$HOOK/unit.o" "$HOOK/hooks_gen.o" $HOOK_OBJS
echo "built $OUT/tvh_hook.exe"
