#!/bin/sh
# Build everything, into three directories:
#
#   build/bin     the two libraries and the speak window -- what you use
#   build/check   the verification binaries, among them tvh.exe (the
#                 oracle, which drives the original DLL) and tvh_hook.exe
#                 (the same with the decompiled C patched in over it)
#   build/obj     intermediates; safe to delete at any time
#
# Those two need a copy of the original to *run*, though not to build; they
# are what the byte-exact comparison is made against.  The standalone build
# below needs nothing but this repository.
#
# Uses the x86_64 mingw toolchain in freestanding -m32 mode: no 32-bit
# libc/libgcc is installed, so we link against msvcrt.dll/kernel32.dll import
# libraries generated by dlltool from harness/rt/*.def.
set -e
cd "$(dirname "$0")/.."
# Three directories, so that what came out of a build is not mixed up
# with how it got there:
#   bin    what you would use
#   check  the verification binaries; tools/difftest.py drives these
#   obj    intermediates, one directory per way the sources compile
OUT=build/bin
CHECK=build/check
OBJ=build/obj
GEN=$OBJ/gen
HOOK=$OBJ/hook
RT=$OBJ/rt
mkdir -p "$OUT" "$CHECK" "$GEN" "$HOOK/obj" "$RT"

# Windows locks a DLL while anything has it loaded, and an executable
# while it is running, so a build with the speak window open dies in the
# linker with "cannot open output file".  Say what actually happened.
for f in "$OUT/tvtts.dll" "$OUT/tvtts64.dll" "$OUT/speakwin.exe"; do
  # opening for append writes nothing, but still fails on a locked file
  if [ -e "$f" ] && ! ( true >> "$f" ) 2>/dev/null; then
    echo "Cannot write $f: it is in use, or not writable." >&2
    echo "Close the speak window, or whatever else has it open, and" >&2
    echo "build again.  Nothing has been changed." >&2
    exit 1
  fi
done
CFLAGS="-m32 -std=gnu11 -O2 -g -Wall -Wno-unused-function -D__USE_MINGW_ANSI_STDIO=0 \
  -fno-asynchronous-unwind-tables -fno-stack-protector -fno-builtin-printf -fwrapv -fno-strict-aliasing \
  -Iharness"

for lib in kernel32 msvcrt user32; do
  if [ ! -f "$RT/lib$lib.a" ] || [ "harness/rt/$lib.def" -nt "$RT/lib$lib.a" ]; then
    dlltool -m i386 --as-flags=--32 -k -d "harness/rt/$lib.def" -l "$RT/lib$lib.a"
  fi
done

# RT_MIN is process startup and the bits of libgcc a freestanding -m32 build
# needs; the harness tools add the PE loader and its sandbox on top of it.
RT_MIN=""
RT_TOOL=""
for src in harness/rt/start.c harness/rt/libgcc32.c harness/rt/chkstk.S \
           harness/peload.c harness/sandbox.c harness/coverage.c; do
  obj="$RT/$(basename "$src" | sed 's/\.[cS]$/.o/')"
  gcc $CFLAGS -c "$src" -o "$obj"
  case "$src" in harness/rt/*) RT_MIN="$RT_MIN $obj" ;; esac
  RT_TOOL="$RT_TOOL $obj"
done
RTLIBS="$RT_TOOL"

link() { # link <exe> <extra ld args...>
  exe=$1; shift
  # Fixed base, no relocations: hook code calls/jumps straight to absolute
  # addresses inside the DLL, which must not shift if the exe were rebased.
  ld -m i386pe --subsystem console -e _mainCRTStartup@0 --stack 0x800000 \
    --disable-dynamicbase --disable-reloc-section \
    -o "$exe" "$@" $RTLIBS "$RT/libmsvcrt.a" "$RT/libkernel32.a" "$RT/libuser32.a"
}

# --- oracle -----------------------------------------------------------------
gcc $CFLAGS -c harness/tvh.c -o "$OBJ/tvh.o"
link "$CHECK/tvh.exe" "$OBJ/tvh.o"
echo "built $CHECK/tvh.exe"

# --- hook build ---------------------------------------------------------------
for f in src/*.fields; do
  python tools/gen_struct.py "$f" "$GEN/$(basename "$f" .fields)_struct.h"
done
HOOK_OBJS=""
for src in $(find src -name '*.c' -not -path 'src/port/*' | sort); do
  obj="$HOOK/obj/$(echo "$src" | sed 's|^src/||; s|/|_|g; s|\.c$|.o|')"
  gcc $CFLAGS -DTV_HOOK_BUILD -Isrc -I"$GEN" -c "$src" -o "$obj"
  HOOK_OBJS="$HOOK_OBJS $obj"
done
python tools/gen_hookmap.py src "$HOOK/hooks_gen.c" "$HOOK/defsyms.txt" $HOOK_OBJS
gcc $CFLAGS -c "$HOOK/hooks_gen.c" -o "$HOOK/hooks_gen.o"
gcc $CFLAGS -c harness/hooks.c -o "$HOOK/hooks.o"
gcc $CFLAGS -DTV_HOOK_BUILD -Isrc -I"$GEN" -c harness/unit.c -o "$HOOK/unit.o"
gcc $CFLAGS -DTV_WITH_HOOKS -c harness/tvh.c -o "$HOOK/tvh_hook.o"
link "$CHECK/tvh_hook.exe" @"$HOOK/defsyms.txt" "$HOOK/tvh_hook.o" "$HOOK/hooks.o" \
  "$HOOK/unit.o" "$HOOK/hooks_gen.o" $HOOK_OBJS
echo "built $CHECK/tvh_hook.exe"

# --- Spanish hook build -------------------------------------------------------
# The same trick against CGRM_ES.DLL: every function written in es/ is patched
# over the original and the audio has to come out identical.  Spanish is a
# separate decompilation with its own struct layout, so it gets its own struct
# header, its own hook map and its own executable; nothing is shared with src/
# but tv_common.h.  Skipped when there is no Spanish C yet.
if [ -n "$(find es -name '*.c' 2>/dev/null)" ]; then
  HOOKES=$OBJ/hook_es
  mkdir -p "$HOOKES/obj"
  python tools/gen_struct.py es/engine.fields "$GEN/es_engine_struct.h"
  ES_OBJS=""
  for src in $(find es -name '*.c' | sort); do
    obj="$HOOKES/obj/$(echo "$src" | sed 's|^es/||; s|/|_|g; s|\.c$|.o|')"
    gcc $CFLAGS -DTV_HOOK_BUILD -Ies -Isrc -I"$GEN" -c "$src" -o "$obj"
    ES_OBJS="$ES_OBJS $obj"
  done
  python tools/gen_hookmap.py es "$HOOKES/hooks_gen.c" "$HOOKES/defsyms.txt" $ES_OBJS
  gcc $CFLAGS -c "$HOOKES/hooks_gen.c" -o "$HOOKES/hooks_gen.o"
  gcc $CFLAGS -DTV_WITH_HOOKS -c harness/tvh.c -o "$HOOKES/tvh_hook.o"
  gcc $CFLAGS -DTV_HOOK_BUILD -Ies -Isrc -I"$GEN" -c harness/unit_es.c -o "$HOOKES/unit_es.o"
  link "$CHECK/tvh_hook_es.exe" @"$HOOKES/defsyms.txt" "$HOOKES/tvh_hook.o" \
    "$HOOK/hooks.o" "$HOOKES/unit_es.o" "$HOOKES/hooks_gen.o" $ES_OBJS
  echo "built $CHECK/tvh_hook_es.exe"
fi

# --- standalone build ---------------------------------------------------------
# No Centigram binary anywhere in here.  The engine is the C in src/, and the
# constant tables it reads are committed under data/ -- see NOTICE for whose
# work those are.  Set TV_DLL to build from your own copy of the original
# instead; tools/extract_data.py says why the two are interchangeable.
DATA=${TV_DLL:-${TV_DATA:-data/en/engine.tvdata}}
if [ ! -f "$DATA" ]; then
  echo "no $DATA: set TV_DATA or TV_DLL, or run tools/extract_data.py" >&2
  exit 1
fi
PORT=$OBJ/port
mkdir -p "$PORT/obj"
PORT_OBJS=""
for src in $(find src -name '*.c' | sort); do
  obj="$PORT/obj/$(echo "$src" | sed 's|^src/||; s|/|_|g; s|\.c$|.o|')"
  gcc $CFLAGS -Isrc -Iinclude -I"$GEN" -c "$src" -o "$obj"
  PORT_OBJS="$PORT_OBJS $obj"
done
python tools/gen_data.py "$DATA" src "$GEN/tvdata.s" $PORT_OBJS
gcc $CFLAGS -c "$GEN/tvdata.s" -o "$PORT/obj/tvdata.o"
RTLIBS="$RT_MIN"
link "$CHECK/tv.exe" $PORT_OBJS "$PORT/obj/tvdata.o"
echo "built $CHECK/tv.exe"

# --- library tests ------------------------------------------------------------
# Everything but the CLI front end, plus the test program in its place.
LIB_OBJS=$(echo "$PORT_OBJS" | tr ' ' '
' | grep -v 'port_main\.o$' | tr '
' ' ')
gcc $CFLAGS -Isrc -Iinclude -I"$GEN" -c tests/api_test.c -o "$PORT/obj/api_test.o"
link "$CHECK/api_test.exe" "$PORT/obj/api_test.o" $LIB_OBJS "$PORT/obj/tvdata.o"
echo "built $CHECK/api_test.exe"

# --- the shared library -------------------------------------------------------
# Everything the CLI links, minus the CLI, plus a DLL entry point.  Only the
# names in harness/rt/tvtts.def are exported, so the engine's own symbols stay
# private; they are plain cdecl names, which is what ctypes and P/Invoke want.
gcc $CFLAGS -c harness/rt/dllmain.c -o "$PORT/obj/dllmain.o"
ld -m i386pe --shared --subsystem console -e _DllMainCRTStartup@12   --disable-dynamicbase --disable-reloc-section   --out-implib "$OUT/libtvtts.a" -o "$OUT/tvtts.dll"   "$PORT/obj/dllmain.o" $LIB_OBJS "$PORT/obj/tvdata.o"   "$RT/libgcc32.o" "$RT/chkstk.o" "$RT/libmsvcrt.a" "$RT/libkernel32.a"   harness/rt/tvtts.def
echo "built $OUT/tvtts.dll"

# The same tests again, this time across the DLL boundary, so the exports and
# the calling convention are exercised rather than assumed.
ld -m i386pe --subsystem console -e _mainCRTStartup@0 --stack 0x800000   --disable-dynamicbase --disable-reloc-section   -o "$CHECK/api_test_dll.exe" "$PORT/obj/api_test.o" $RT_MIN   "$OUT/libtvtts.a" "$RT/libmsvcrt.a" "$RT/libkernel32.a"
echo "built $CHECK/api_test_dll.exe"

# --- 64-bit ---------------------------------------------------------------
# The first 64-bit TruVoice.  Nothing freestanding here: at 64 bits a normal
# hosted toolchain is available, so this is an ordinary gcc build against the
# system C runtime.  The data comes out of the image with eight-byte pointers
# (tools/gen_data.py --bits 64).
P64=$OBJ/port64
mkdir -p "$P64/obj"
CF64="-m64 -std=gnu11 -O2 -g -Wall -Wno-unused-function -fwrapv \
  -fno-strict-aliasing -Isrc -Iinclude -I$GEN"
OBJ64=""
for src in $(find src -name '*.c' | sort); do
  obj="$P64/obj/$(echo "$src" | sed 's|^src/||; s|/|_|g; s|\.c$|.o|')"
  gcc $CF64 -c "$src" -o "$obj"
  OBJ64="$OBJ64 $obj"
done
python tools/gen_data.py "$DATA" src "$GEN/tvdata64.s" $OBJ64
gcc -m64 -c "$GEN/tvdata64.s" -o "$P64/obj/tvdata.o"
gcc -m64 -o "$CHECK/tv64.exe" $OBJ64 "$P64/obj/tvdata.o"
echo "built $CHECK/tv64.exe"

LIB64=$(echo "$OBJ64" | tr ' ' '\n' | grep -v 'port_main\.o$' | tr '\n' ' ')
gcc $CF64 -c tests/api_test.c -o "$P64/obj/api_test.o"
gcc -m64 -o "$CHECK/api_test64.exe" "$P64/obj/api_test.o" $LIB64 "$P64/obj/tvdata.o"
echo "built $CHECK/api_test64.exe"

gcc -m64 -shared -o "$OUT/tvtts64.dll" $LIB64 "$P64/obj/tvdata.o" \
  -Wl,--out-implib,"$OUT/libtvtts64.a" harness/rt/tvtts.def
echo "built $OUT/tvtts64.dll"

# --- the speak window ---------------------------------------------------------
# A Win32 GUI over the library: type text, pick a voice, hear it, save a WAV.
# Built 64-bit against tvtts64.dll with an ordinary hosted toolchain -- none of
# the freestanding -m32 machinery above applies to it.  The import library is
# named by path rather than with -L, which is shorter than telling the
# linker a directory and then a name that is only in it.
gcc -m64 -O2 -Wall -Wextra -municode -mwindows -o "$OUT/speakwin.exe" \
  gui/speakwin.c -Iinclude "$OUT/libtvtts64.a" \
  -lcomctl32 -lwinmm -lcomdlg32 -lgdi32
echo "built $OUT/speakwin.exe"

# The build prints a line per target as it goes, which is a lot to read
# back.  This is the part worth reading: what exists now and where.
echo
echo "Ready to use, in $OUT:"
for f in tvtts.dll tvtts64.dll speakwin.exe; do
  [ -f "$OUT/$f" ] && echo "    $f"
done
echo "  link against it with $OUT/libtvtts.a or $OUT/libtvtts64.a"
echo "  the NVDA add-on is a separate step: python tools/make_addon.py"
echo
echo "Verification binaries, in $CHECK: $(ls "$CHECK" | tr '\n' ' ')"
echo "  run them with python tools/difftest.py"
echo
echo "Intermediates are under $OBJ and can be deleted at any time."
