#!/bin/sh
# Build the 32-bit harness tools into build/harness/:
#   tvh.exe       drives the original CGRM_EN.DLL engine (the oracle)
#   tvh_hook.exe  same, with every decompiled function from src/ hooked in
#
# Uses the x86_64 mingw toolchain in freestanding -m32 mode: no 32-bit
# libc/libgcc is installed, so we link against msvcrt.dll/kernel32.dll import
# libraries generated by dlltool from harness/rt/*.def.
set -e
cd "$(dirname "$0")/.."
OUT=build/harness
GEN=build/gen
HOOK=build/hook
mkdir -p "$OUT" "$GEN" "$HOOK/obj"
CFLAGS="-m32 -std=gnu11 -O2 -g -Wall -Wno-unused-function -D__USE_MINGW_ANSI_STDIO=0 \
  -fno-asynchronous-unwind-tables -fno-stack-protector -fno-builtin-printf -fwrapv -fno-strict-aliasing \
  -Iharness"

for lib in kernel32 msvcrt user32; do
  if [ ! -f "$OUT/lib$lib.a" ] || [ "harness/rt/$lib.def" -nt "$OUT/lib$lib.a" ]; then
    dlltool -m i386 --as-flags=--32 -k -d "harness/rt/$lib.def" -l "$OUT/lib$lib.a"
  fi
done

# RT_MIN is process startup and the bits of libgcc a freestanding -m32 build
# needs; the harness tools add the PE loader and its sandbox on top of it.
RT_MIN=""
RT_TOOL=""
for src in harness/rt/start.c harness/rt/libgcc32.c harness/rt/chkstk.S \
           harness/peload.c harness/sandbox.c harness/coverage.c; do
  obj="$OUT/$(basename "$src" | sed 's/\.[cS]$/.o/')"
  gcc $CFLAGS -c "$src" -o "$obj"
  case "$src" in harness/rt/*) RT_MIN="$RT_MIN $obj" ;; esac
  RT_TOOL="$RT_TOOL $obj"
done
RT="$RT_TOOL"

link() { # link <exe> <extra ld args...>
  exe=$1; shift
  # Fixed base, no relocations: hook code calls/jumps straight to absolute
  # addresses inside the DLL, which must not shift if the exe were rebased.
  ld -m i386pe --subsystem console -e _mainCRTStartup@0 --stack 0x800000 \
    --disable-dynamicbase --disable-reloc-section \
    -o "$exe" "$@" $RT "$OUT/libmsvcrt.a" "$OUT/libkernel32.a" "$OUT/libuser32.a"
}

# --- oracle -----------------------------------------------------------------
gcc $CFLAGS -c harness/tvh.c -o "$OUT/tvh.o"
link "$OUT/tvh.exe" "$OUT/tvh.o"
echo "built $OUT/tvh.exe"

# --- hook build ---------------------------------------------------------------
for f in src/*.fields; do
  python tools/gen_struct.py "$f" "$GEN/$(basename "$f" .fields)_struct.h"
done
HOOK_OBJS=""
for src in $(find src -name '*.c' -not -path 'src/port/*' | sort); do
  obj="$HOOK/obj/$(echo "$src" | sed 's|^src/||; s|/|_|g; s|\.c$|.o|')"
  gcc $CFLAGS -DTV_HOOK_BUILD -Isrc -I"$GEN" -c "$src" -o "$obj"
  HOOK_OBJS="$HOOK_OBJS $obj"
done
python tools/gen_hookmap.py src "$HOOK/hooks_gen.c" "$HOOK/defsyms.txt" $HOOK_OBJS
gcc $CFLAGS -c "$HOOK/hooks_gen.c" -o "$HOOK/hooks_gen.o"
gcc $CFLAGS -c harness/hooks.c -o "$HOOK/hooks.o"
gcc $CFLAGS -DTV_HOOK_BUILD -Isrc -I"$GEN" -c harness/unit.c -o "$HOOK/unit.o"
gcc $CFLAGS -DTV_WITH_HOOKS -c harness/tvh.c -o "$HOOK/tvh_hook.o"
link "$OUT/tvh_hook.exe" @"$HOOK/defsyms.txt" "$HOOK/tvh_hook.o" "$HOOK/hooks.o" \
  "$HOOK/unit.o" "$HOOK/hooks_gen.o" $HOOK_OBJS
echo "built $OUT/tvh_hook.exe"

# --- standalone build ---------------------------------------------------------
# No DLL at run time: the engine is the C in src/, and the constant tables it
# reads are pulled out of the original image here, at build time.
DLL=${TV_DLL:-TruVoice/CGRM_EN.DLL}
if [ ! -f "$DLL" ]; then
  echo "no $DLL: skipping the standalone build" >&2
  exit 0
fi
PORT=build/port
mkdir -p "$PORT/obj"
PORT_OBJS=""
for src in $(find src -name '*.c' | sort); do
  obj="$PORT/obj/$(echo "$src" | sed 's|^src/||; s|/|_|g; s|\.c$|.o|')"
  gcc $CFLAGS -Isrc -Iinclude -I"$GEN" -c "$src" -o "$obj"
  PORT_OBJS="$PORT_OBJS $obj"
done
python tools/gen_data.py "$DLL" src "$GEN/tvdata.s" $PORT_OBJS
gcc $CFLAGS -c "$GEN/tvdata.s" -o "$PORT/obj/tvdata.o"
RT="$RT_MIN"
link "$OUT/tv.exe" $PORT_OBJS "$PORT/obj/tvdata.o"
echo "built $OUT/tv.exe"

# --- library tests ------------------------------------------------------------
# Everything but the CLI front end, plus the test program in its place.
LIB_OBJS=$(echo "$PORT_OBJS" | tr ' ' '
' | grep -v 'port_main\.o$' | tr '
' ' ')
gcc $CFLAGS -Isrc -Iinclude -I"$GEN" -c tests/api_test.c -o "$PORT/obj/api_test.o"
link "$OUT/api_test.exe" "$PORT/obj/api_test.o" $LIB_OBJS "$PORT/obj/tvdata.o"
echo "built $OUT/api_test.exe"

# --- the shared library -------------------------------------------------------
# Everything the CLI links, minus the CLI, plus a DLL entry point.  Only the
# names in harness/rt/tvtts.def are exported, so the engine's own symbols stay
# private; they are plain cdecl names, which is what ctypes and P/Invoke want.
gcc $CFLAGS -c harness/rt/dllmain.c -o "$PORT/obj/dllmain.o"
ld -m i386pe --shared --subsystem console -e _DllMainCRTStartup@12   --disable-dynamicbase --disable-reloc-section   --out-implib "$OUT/libtvtts.a" -o "$OUT/tvtts.dll"   "$PORT/obj/dllmain.o" $LIB_OBJS "$PORT/obj/tvdata.o"   "$OUT/libgcc32.o" "$OUT/chkstk.o" "$OUT/libmsvcrt.a" "$OUT/libkernel32.a"   harness/rt/tvtts.def
echo "built $OUT/tvtts.dll"

# The same tests again, this time across the DLL boundary, so the exports and
# the calling convention are exercised rather than assumed.
ld -m i386pe --subsystem console -e _mainCRTStartup@0 --stack 0x800000   --disable-dynamicbase --disable-reloc-section   -o "$OUT/api_test_dll.exe" "$PORT/obj/api_test.o" $RT_MIN   "$OUT/libtvtts.a" "$OUT/libmsvcrt.a" "$OUT/libkernel32.a"
echo "built $OUT/api_test_dll.exe"

# --- 64-bit ---------------------------------------------------------------
# The first 64-bit TruVoice.  Nothing freestanding here: at 64 bits a normal
# hosted toolchain is available, so this is an ordinary gcc build against the
# system C runtime.  The data comes out of the image with eight-byte pointers
# (tools/gen_data.py --bits 64).
P64=build/port64
mkdir -p "$P64/obj"
CF64="-m64 -std=gnu11 -O2 -g -Wall -Wno-unused-function -fwrapv \
  -fno-strict-aliasing -Isrc -Iinclude -I$GEN"
OBJ64=""
for src in $(find src -name '*.c' | sort); do
  obj="$P64/obj/$(echo "$src" | sed 's|^src/||; s|/|_|g; s|\.c$|.o|')"
  gcc $CF64 -c "$src" -o "$obj"
  OBJ64="$OBJ64 $obj"
done
python tools/gen_data.py "$DLL" src "$GEN/tvdata64.s" $OBJ64
gcc -m64 -c "$GEN/tvdata64.s" -o "$P64/obj/tvdata.o"
gcc -m64 -o "$OUT/tv64.exe" $OBJ64 "$P64/obj/tvdata.o"
echo "built $OUT/tv64.exe"

LIB64=$(echo "$OBJ64" | tr ' ' '\n' | grep -v 'port_main\.o$' | tr '\n' ' ')
gcc $CF64 -c tests/api_test.c -o "$P64/obj/api_test.o"
gcc -m64 -o "$OUT/api_test64.exe" "$P64/obj/api_test.o" $LIB64 "$P64/obj/tvdata.o"
echo "built $OUT/api_test64.exe"

gcc -m64 -shared -o "$OUT/tvtts64.dll" $LIB64 "$P64/obj/tvdata.o" \
  -Wl,--out-implib,"$OUT/libtvtts64.a" harness/rt/tvtts.def
echo "built $OUT/tvtts64.dll"
