#ifndef HOOKS_H
#define HOOKS_H
#include <stdint.h>

typedef struct {
    uint32_t addr;    /* original function address in the DLL */
    void *fn;         /* decompiled replacement */
    const char *name;
} hook_entry;

extern const hook_entry tv_hooks[]; /* generated by tools/gen_hookmap.py */

int hooks_install(const char *spec, int verbose);

#endif
