"""Generate C struct definitions from offset-annotated field lists.

Usage: python tools/gen_struct.py <in.fields> <out.h>

The .fields format lets us describe a structure incrementally, by the
offsets the original code uses, without hand-maintaining padding:

    # comment
    struct Engine 0x9180            -- name and total size (32-bit layout)
    0x0000 uint8_t   busy           # optional comment
    0x1a40 InputSeg  seg[10]
    0x2128 int16_t  *out_buf        -- pointers are 4 bytes in the 32-bit layout
    end

Gaps become `uint8_t unk_XXXX[n]` members.  For every field a static
assertion checks the offset when compiling the 32-bit hook build (where the
layout must match the original DLL exactly).  In other builds pointer fields
may grow, which is fine because all access goes through member names.

Types known to the generator: fixed-width ints, char, float, double, any
pointer (4 bytes), and every struct defined earlier in the same or an
included .fields file ("include other.fields").
"""
import os
import re
import sys

BUILTIN = {
    "uint8_t": 1, "int8_t": 1, "char": 1, "uint16_t": 2, "int16_t": 2,
    "uint32_t": 4, "int32_t": 4, "float": 4, "double": 8, "uint64_t": 8,
    "int64_t": 8,
}
ALIGN = dict(BUILTIN)
ALIGN["double"] = 8


def parse(path, structs, order, seen_files):
    path = os.path.abspath(path)
    if path in seen_files:
        return
    seen_files.add(path)
    cur = None
    for lineno, raw in enumerate(open(path, encoding="utf-8"), 1):
        line = raw.split("#", 1)
        body = line[0].strip()
        comment = line[1].strip() if len(line) > 1 else ""
        if not body:
            continue
        parts = body.split()
        if parts[0] == "include":
            parse(os.path.join(os.path.dirname(path), parts[1]), structs, order, seen_files)
            continue
        if parts[0] in ("struct", "union"):
            cur = {"kind": parts[0], "name": parts[1], "size": int(parts[2], 0),
                   "fields": [], "file": path, "comment": comment}
            continue
        if parts[0] == "end":
            structs[cur["name"]] = cur
            order.append(cur["name"])
            cur = None
            continue
        if cur is None:
            raise SystemExit("%s:%d: field outside struct" % (path, lineno))
        off = int(parts[0], 0)
        decl = " ".join(parts[1:])
        m = re.fullmatch(r"(.+?)\s*(\*+)?\s*([A-Za-z_]\w*)\s*((?:\[[^\]]+\])*)", decl)
        if not m:
            raise SystemExit("%s:%d: cannot parse field %r" % (path, lineno, decl))
        typ, stars, name, dims = m.group(1).strip(), m.group(2) or "", m.group(3), m.group(4)
        count = 1
        for d in re.findall(r"\[([^\]]+)\]", dims):
            count *= int(d, 0)
        cur["fields"].append({"off": off, "type": typ, "stars": stars, "name": name,
                              "dims": dims, "count": count, "comment": comment,
                              "line": lineno})


def type_size(typ, stars, structs):
    if stars:
        return 4, 4
    if typ in BUILTIN:
        return BUILTIN[typ], ALIGN[typ]
    if typ in structs:
        s = structs[typ]
        al = 1
        for f in s["fields"]:
            al = max(al, type_size(f["type"], f["stars"], structs)[1])
        return s["size"], al
    raise SystemExit("unknown type %s" % typ)


def emit(structs, order, out_path, own_files):
    lines = []
    guard = "TV_GEN_" + re.sub(r"\W", "_", os.path.basename(out_path)).upper()
    lines.append("/* Generated by tools/gen_struct.py -- do not edit. */")
    lines.append("#ifndef %s" % guard)
    lines.append("#define %s" % guard)
    lines.append("#include <stddef.h>")
    lines.append("#include <stdint.h>")
    lines.append('#include "tv_common.h"')
    lines.append("")
    for name in order:
        s = structs[name]
        lines.append("typedef %s %s %s;" % (s["kind"], name, name))
    lines.append("")
    asserts = []
    for name in order:
        s = structs[name]
        if s["file"] not in own_files:
            continue
        if s["comment"]:
            lines.append("/* %s */" % s["comment"])
        lines.append("%s %s {" % (s["kind"], name))
        pos = 0
        fields = sorted(s["fields"], key=lambda f: f["off"])
        if s["kind"] == "union":
            for f in fields:
                t = f["type"] + (" " + f["stars"] if f["stars"] else "")
                lines.append("    %s %s%s;" % (t, f["name"], f["dims"]))
        else:
            for f in fields:
                size, al = type_size(f["type"], f["stars"], structs)
                total = size * f["count"]
                if f["off"] < pos:
                    raise SystemExit("%s: field %s at 0x%x overlaps previous (ends 0x%x)" %
                                     (name, f["name"], f["off"], pos))
                if f["off"] % al:
                    raise SystemExit("%s: field %s at 0x%x is misaligned for %s" %
                                     (name, f["name"], f["off"], f["type"]))
                if f["off"] > pos:
                    lines.append("    uint8_t unk_%04x[0x%x];" % (pos, f["off"] - pos))
                t = f["type"] + (" " + f["stars"] if f["stars"] else "")
                cmt = "  /* 0x%04x%s */" % (f["off"], " " + f["comment"] if f["comment"] else "")
                lines.append("    %s %s%s;%s" % (t, f["name"], f["dims"], cmt))
                pos = f["off"] + total
                asserts.append("TV_LAYOUT_ASSERT(offsetof(%s, %s) == 0x%x);" % (name, f["name"], f["off"]))
            if pos < s["size"]:
                lines.append("    uint8_t unk_%04x[0x%x];" % (pos, s["size"] - pos))
            elif pos > s["size"]:
                raise SystemExit("%s: fields end at 0x%x beyond size 0x%x" % (name, pos, s["size"]))
        lines.append("};")
        lines.append("")
        asserts.append("TV_LAYOUT_ASSERT(sizeof(%s) == 0x%x);" % (name, s["size"]))
    lines.append("/* Exact 32-bit layout checks (hook build only). */")
    lines.extend(asserts)
    lines.append("")
    lines.append("#endif")
    with open(out_path, "w", encoding="utf-8", newline="\n") as fp:
        fp.write("\n".join(lines) + "\n")


def main():
    src, out = sys.argv[1], sys.argv[2]
    structs, order = {}, []
    seen = set()
    parse(src, structs, order, seen)
    emit(structs, order, out, {os.path.abspath(src)})


if __name__ == "__main__":
    main()
