"""Keep two engines' symbols apart inside one library.

Usage: python tools/gen_rename.py <srcdir> <prefix> <out.h>

The library carries one engine per language, and the two decompilations use the
same names for the same jobs -- both have an `Engine_Feed`, because both engines
have one, and they are different functions on different objects.  One image
cannot hold both under one name.

So one of them is compiled with every name of its own prefixed.  This writes the
header that does it: a #define per annotated symbol, force-included with -include
when that language is built into the shared library.  The hook build does not use
it, because gen_hookmap.py has to see the real names to bind them to the DLL.

What gets renamed is exactly what the `@0x...` annotations name -- the engine's
own functions and tables -- plus tv_data, which tools/gen_data.py emits for
whichever language it was run for.  Nothing else: a call to memcpy or to
tvtts_speak_bytes has to keep pointing where it pointed.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gen_data import scan  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

#: Names that need the prefix but carry no `@0x` annotation to be found by:
#: tv_data, which tools/gen_data.py emits per language, and the handful of
#: helpers a decompilation writes itself because the original reached a field by
#: offset rather than by name.  Both trees define these, so both would clash.
EXTRA = ("tv_data", "Engine_ZeroDwordIfMinus1")


def main():
    if len(sys.argv) != 4:
        sys.exit(__doc__.strip().split("\n")[2])
    srcdir, prefix, out = sys.argv[1], sys.argv[2], sys.argv[3]
    dirs = ",".join(os.path.join(ROOT, d) for d in srcdir.split(","))
    names = sorted(set(scan(dirs)) | set(EXTRA))

    os.makedirs(os.path.dirname(out) or ".", exist_ok=True)
    with open(out, "w", newline="\n") as fp:
        fp.write("/* Generated by tools/gen_rename.py -- do not edit.\n"
                 " * Every name %s/ defines, prefixed with %s, so that this\n"
                 " * engine and the other one can be in one library. */\n"
                 % (srcdir, prefix))
        fp.write("#ifndef TV_RENAME_%s_H\n#define TV_RENAME_%s_H\n"
                 % (prefix.upper().strip("_"), prefix.upper().strip("_")))
        for n in names:
            fp.write("#define %s %s%s\n" % (n, prefix, n))
        fp.write("#endif\n")
    print("gen_rename: %d symbols prefixed with %s -> %s"
          % (len(names), prefix, os.path.relpath(out, ROOT)))


if __name__ == "__main__":
    main()
