"""Generate the synthesiser tables for OpenTV's extra sample rate.

Usage: python tools/gen_synth_hifi.py [--rate HZ] [src/engine/syn_hifi.c]

TruVoice shipped resonator tables for two sample rates, 8 kHz and 11.025
kHz, chosen in Synth_InitFilters.  It has none for anything else because
Centigram never offered one.  These are OpenTV's, computed rather than
lifted: the formulas below reproduce both of the original's sets exactly,
which is what makes evaluating them at a third rate trustworthy.  The rate
is a parameter, so moving it is a one-line change here and one in
src/engine.h -- the generated file static-asserts that the two agree.

    t6[i] = round( 8192 * exp(-4*pi*i/Fs) )     pole radius r, i = bandwidth/4 Hz
    t7[i] = round( 8192 * exp(-8*pi*i/Fs) )     the r^2 term
    t8[i] = round(16384 * cos(2*pi*8*i/Fs) )    2*cos(theta), i = frequency/8 Hz

A Klatt two-pole section, in Q13.  `--verify` checks the formulas against
the original's own 8 kHz and 11.025 kHz tables, all 2120 values.

The tables this does not compute are the ones that are not rate-dependent.
The original's 11 kHz set is uniform where its 8 kHz set has substitutions
in the first few entries -- table 2 entry 0 is 11354 at 11 kHz, which is
also entry 7 and also the initial filt_coef[37] at *both* rates, while 8
kHz uses 5000 instead.  Those are wideband-versus-narrowband values rather
than per-rate ones, so the extra rate shares the 11 kHz ones and only the
three tables above are regenerated.  Table 9 is the one approximation: it is
mildly rate-dependent, 0.25% across the octave from 8 kHz to 11.025 kHz,
and no exact formula for it has been found, so the 11 kHz values are used.
"""
import math
import os
import struct
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FS = 16000

#: Where the original's two sets live, for --verify.
ORIG = {8000: (0x101219c8, 0x10121f68, 0x10122d28),
        11025: (0x101216f8, 0x10121c98, 0x10122238)}

#: The engine has one fixed resonator whose coefficients are per-rate
#: constants rather than table lookups: filt_coef[12] and [13] (a[10], a[11]
#: in the generator, a 2r*cos / r^2 pair) and filt_coef[33], plus syn_2038.
#: Fitting all of them across the original's two rates puts it at 242 Hz
#: with a bandwidth of 102 Hz -- and syn_2038 independently implies the same
#: 102 Hz, which is what says the model is the right shape.  8 kHz comes back
#: exact; 11.025 kHz is within 11 of 30905, so the original's two sets were
#: not computed to quite the same precision.
RES_F = 242.00
RES_BW = 102.07


def t6(fs, n=180):
    return [int(round(8192 * math.exp(-4 * math.pi * i / fs))) for i in range(n)]


def t7(fs, n=180):
    return [int(round(8192 * math.exp(-8 * math.pi * i / fs))) for i in range(n)]


def t8(fs, n=700):
    return [int(round(16384 * math.cos(2 * math.pi * 8 * i / fs))) for i in range(n)]


def syn2038(fs):
    return -int(round(8192 * math.exp(-math.pi * RES_BW / fs)))

def fixed_res(fs):
    """filt_coef[12], [13] and [33] for this rate."""
    r = math.exp(-math.pi * RES_BW / fs)
    return (int(round(32768 * r * math.cos(2 * math.pi * RES_F / fs))),
            int(round(32768 * r * r)))


def verify():
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    from pe32 import Image
    dll = os.path.join(ROOT, "TruVoice", "CGRM_EN.DLL")
    if not os.path.isfile(dll):
        sys.exit("--verify needs %s" % dll)
    img = Image(dll)
    mem = bytes(img.mem)

    def dw(a, n):
        return list(struct.unpack_from("<%di" % n, mem, a - img.base))

    bad = 0
    for fs, (a6, a7, a8) in sorted(ORIG.items()):
        for name, got, want in (("t6", t6(fs), dw(a6, 180)),
                                ("t7", t7(fs), dw(a7, 180)),
                                ("t8", t8(fs), dw(a8, 700))):
            n = sum(1 for x, y in zip(got, want) if x != y)
            bad += n
            print("  Fs=%-6d %s  %d/%d exact" % (fs, name, len(want) - n, len(want)))
    print("all %s" % ("exact" if not bad else "FAILED: %d values differ" % bad))
    return 1 if bad else 0


def emit(path):
    def table(name, vals):
        out = ["const int32_t %s[%d] = {" % (name, len(vals))]
        for i in range(0, len(vals), 8):
            out.append("    " + " ".join("%d," % v for v in vals[i:i + 8]))
        out.append("};")
        return "\n".join(out)

    body = [
        "/*",
        " * The resonator tables for OpenTV's extra sample rate.",
        " *",
        " * Generated by tools/gen_synth_hifi.py -- do not edit.",
        " *",
        " * These are not Centigram's.  TruVoice shipped tables for 8 kHz and",
        " * 11.025 kHz only; these are computed from the formulas that reproduce",
        " * both of those exactly, evaluated at %d.  See the generator and" % FS,
        " * docs/VOICES.md.",
        " */",
        '#include "engine.h"',
        "",
        "/* The rate these were generated for must match the engine's. */",
        "typedef char tv_hifi_rate_agrees[(TV_SR_HIFI == %d) ? 1 : -1];" % FS,
        "",
        table("g_synhifi_6", t6(FS)),
        "",
        table("g_synhifi_7", t7(FS)),
        "",
        table("g_synhifi_8", t8(FS)),
        "",
        "/* The fixed resonator frame.c pairs with a frequency from track 16. */",
        "const int32_t g_synhifi_2038 = %d;" % syn2038(FS),
        "",
        "/* filt_coef[12], [13] and [33]: the same resonator, and the only",
        " * entries of the initial coefficient array that depend on the rate",
        " * and are never rewritten per frame. */",
        "const int32_t g_synhifi_c12 = %d;" % fixed_res(FS)[0],
        "const int32_t g_synhifi_c13 = %d;" % fixed_res(FS)[1],
        "",
    ]
    with open(path, "w", newline="\n") as fp:
        fp.write("\n".join(body))
    print("wrote %s (%d values)" % (os.path.relpath(path, ROOT), 180 + 180 + 700 + 1))
    print("  generated for %d Hz" % FS)
    print("  syn_2038 = %d  (8k had %d, 11k had %d)"
          % (syn2038(FS), syn2038(8000), syn2038(11025)))


def main():
    global FS
    argv = sys.argv[1:]
    if "--rate" in argv:
        i = argv.index("--rate")
        FS = int(argv[i + 1])
        del argv[i:i + 2]
    args = [a for a in argv if a != "--verify"]
    if "--verify" in sys.argv[1:]:
        sys.exit(verify())
    out = args[0] if args else os.path.join(ROOT, "src", "engine", "syn_hifi.c")
    emit(out)


if __name__ == "__main__":
    main()
