# -*- coding: utf-8 -*-
"""Project upstream's devoicing tables into the mora alphabet the renderer uses.

    python tools/gen_ja_devoice.py

Writes build/Japanese_test/jp_devoice_tab.py and
lang/jpn/port/ja_devoice_tab.{c,h}.

njd_set_unvoiced_vowel's rule 5 runs three CANDIDATE classes, each with its own
list of following morae, and the exclusions are the whole point: /su/ does not
devoice before another s-row mora and /fu hi fi/ not before an h-row one,
because that would leave two fricatives with nothing between them.  The
analyser has those tables in upstream's katakana.  The string-level fallback in
jp_speak.build and ja_frame.c works in the romaji mora alphabet instead, and
had none of it -- it devoiced before any voiceless onset, so romaji `sushi`
devoiced its /su/ where 寿司 does not.

TWO THINGS DO NOT SURVIVE ROMANISATION and are resolved here rather than at
run time:

  * The FOLLOWING mora is matched by PREFIX in katakana -- キャ passes a list
    containing キ because it starts with it -- and 'kya' does not start with
    'ki'.  So the prefix test is expanded here against the 159-mora inventory
    and the run-time test is plain set membership.

  * Some foreign katakana morae COLLAPSE onto ordinary ones under the romaji
    parser: テュ comes back as 'yu' and トゥ as 'to'.  Taken at face value
    those would make /yu/ a devoicing candidate, which has a voiced onset, and
    /to/ one as well, which is not a high vowel.  Each projected mora is
    therefore checked against the physical precondition it must satisfy, and
    what gets dropped is printed rather than silently discarded.

The filters are a restatement of the data, not an invention: the script
asserts that every follower upstream lists has a voiceless onset and that every
candidate it lists is a high vowel after one, so anything failing the test came
from the projection rather than from upstream.
"""
from __future__ import print_function

import io
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, os.path.join(ROOT, 'build', 'Japanese_test'))

import jp_mora as M        # noqa: E402
import jp_njd as N         # noqa: E402
import jp_speak as S       # noqa: E402

PY_OUT = os.path.join(ROOT, 'build', 'Japanese_test', 'jp_devoice_tab.py')
C_OUT = os.path.join(ROOT, 'lang', 'jpn', 'port', 'ja_devoice_tab.c')
H_OUT = os.path.join(ROOT, 'lang', 'jpn', 'port', 'ja_devoice_tab.h')

# romaji onset -> the C enumerator.  '' is the empty onset, which the C calls
# JA_C_NONE and never reaches here, since every candidate has a consonant.
CONS = ['', 'k', 'ky', 'g', 'gy', 't', 'd', 'p', 'py', 'b', 'by', 'v',
        's', 'sh', 'z', 'j', 'ch', 'ts', 'h', 'hy', 'f',
        'n', 'ny', 'm', 'my', 'r', 'ry', 'w', 'y']
VOWELS = ['a', 'i', 'u', 'e', 'o']


def c_name(onset):
    return 'JA_C_NONE' if onset == '' else 'JA_C_' + onset.upper()


def one(kata):
    """The katakana mora as a single romaji mora, or None if it is not one."""
    r = M.to_morae(kata)
    return r[0] if len(r) == 1 else None


def is_candidate(r):
    """A high vowel after a voiceless consonant."""
    if r is None:
        return False
    c, v = M.split(r)
    return v in 'iu' and c in S.VOICELESS


def has_voiceless_onset(r):
    if r is None:
        return False
    c, v = M.split(r)
    return c in S.VOICELESS


def project():
    cand, follow, dropped = [], [], []
    for cls, (cs, allow) in enumerate(zip(N.CAND, N.NEXT), 1):
        keep = set()
        for k in cs:
            r = one(k)
            if is_candidate(r):
                keep.add(r)
            else:
                dropped.append(('candidate %d' % cls, k, r))
        cand.append(keep)

        keep = set()
        for m in N._MORA_LIST:
            if not any(m.startswith(a) for a in allow):
                continue
            r = one(m)
            if has_voiceless_onset(r):
                keep.add(r)
            else:
                dropped.append(('follower %d' % cls, m, r))
        follow.append(keep)
    return cand, follow, dropped


def check_upstream():
    """Every follower upstream lists must pass the filter.

    If one did not, the filter would be removing upstream's data rather than
    the projection's artefacts, and the tables below would be wrong.  The
    candidates are deliberately NOT asserted: four of them are foreign morae
    this alphabet cannot spell, and dropping those is the point.
    """
    bad = [a for allow in N.NEXT for a in allow
           if one(a) is None or not has_voiceless_onset(one(a))]
    assert not bad, 'a follower upstream lists is not voiceless: %s' % bad


HEAD = (u'/*\n'
        u' * Generated by tools/gen_ja_devoice.py from Open JTalk 1.11\'s\n'
        u' * njd_set_unvoiced_vowel tables -- do not edit.\n'
        u' *\n'
        u' * Rule 5\'s three candidate classes, projected from upstream\'s\n'
        u' * katakana into the (onset, vowel) pair this port uses.  The\n'
        u' * exclusions are the point: /su/ does not devoice before another\n'
        u' * s-row mora and /fu hi fi/ not before an h-row one, because that\n'
        u' * would leave two fricatives with nothing between them.\n'
        u' *\n'
        u' * The following mora is matched by PREFIX upstream, so the prefix\n'
        u' * test is already expanded here and this is plain membership.\n'
        u' */\n')


def write_py(cand, follow):
    out = [u'# -*- coding: utf-8 -*-\n',
           u'"""Generated by tools/gen_ja_devoice.py -- do not edit.\n\n',
           u'njd_set_unvoiced_vowel rule 5, projected into the romaji mora\n',
           u'alphabet.  CAND[i] is a candidate class, NEXT[i] the morae it\n',
           u'devoices before, with upstream\'s katakana prefix test already\n',
           u'expanded.  The exclusions are the point: /su/ is not followed by\n',
           u'an s-row mora here, nor /fu hi fi/ by an h-row one.\n"""\n',
           u'\n']
    out.append(u'CAND = (\n')
    for s in cand:
        out.append(u'    frozenset([%s]),\n'
                   % ', '.join("'%s'" % r for r in sorted(s)))
    out.append(u')\n\nNEXT = (\n')
    for s in follow:
        items = sorted(s)
        line = u'    frozenset(['
        parts, cur = [], line
        for i, r in enumerate(items):
            piece = u"'%s'%s" % (r, '' if i == len(items) - 1 else ', ')
            if len(cur) + len(piece) > 74:
                parts.append(cur)
                cur = u'               '
            cur += piece
        parts.append(cur + u']),')
        out.append(u'\n'.join(parts) + u'\n')
    out.append(u')\n')
    io.open(PY_OUT, 'w', encoding='utf-8', newline='\n').write(u''.join(out))


def write_c(cand, follow):
    h = [HEAD,
         u'#ifndef JA_DEVOICE_TAB_H\n#define JA_DEVOICE_TAB_H\n\n',
         u'#include "ja.h"\n\n',
         u'/* 0 = not a devoicing candidate, otherwise its class, 1 to 3. */\n',
         u'extern const unsigned char ja_dv_cand[JA_NC][JA_NV];\n\n',
         u'/* Bit (class - 1) set: this mora may follow that class. */\n',
         u'extern const unsigned char ja_dv_follow[JA_NC][JA_NV];\n\n',
         u'#endif\n']
    io.open(H_OUT, 'w', encoding='utf-8', newline='\n').write(u''.join(h))

    cand_at, follow_at = {}, {}
    for i, s in enumerate(cand, 1):
        for r in s:
            cand_at[M.split(r)] = i
    for i, s in enumerate(follow, 1):
        for r in s:
            follow_at.setdefault(M.split(r), 0)
            follow_at[M.split(r)] |= 1 << (i - 1)

    def table(name, lookup, comment):
        rows = [u'/* %s */\n' % comment,
                u'const unsigned char %s[JA_NC][JA_NV] = {\n' % name]
        for onset in CONS:
            vals = [lookup.get((onset, v), 0) for v in VOWELS]
            if any(vals):
                rows.append(u'    [%-10s] = { %s },\n'
                            % (c_name(onset),
                               ', '.join(str(x) for x in vals)))
        rows.append(u'};\n')
        return u''.join(rows)

    c = [HEAD, u'#include "ja_devoice_tab.h"\n\n',
         table('ja_dv_cand', cand_at,
               'the candidate class of each mora, by onset then vowel'),
         u'\n',
         table('ja_dv_follow', follow_at,
               'which classes each mora may follow, as a bitmask')]
    io.open(C_OUT, 'w', encoding='utf-8', newline='\n').write(u''.join(c))


def main():
    check_upstream()
    cand, follow, dropped = project()
    write_py(cand, follow)
    write_c(cand, follow)
    for i, (c, f) in enumerate(zip(cand, follow), 1):
        print('class %d: %d candidates, %d followers' % (i, len(c), len(f)))
        print('   %s' % ' '.join(sorted(c)))
    print()
    print('dropped by the projection (the romaji parser collapses these):')
    seen = set()
    for where, kata, r in dropped:
        if (kata, r) in seen:
            continue
        seen.add((kata, r))
        print('   %-4s -> %-4s' % (kata, r))
    print()
    print('wrote %s' % os.path.relpath(PY_OUT, ROOT))
    print('      %s' % os.path.relpath(C_OUT, ROOT))
    print('      %s' % os.path.relpath(H_OUT, ROOT))
    return 0


if __name__ == '__main__':
    sys.exit(main())
