# -*- coding: utf-8 -*-
"""Turn jp_g2p.py's adaptation tables into C.

    python tools/gen_ja_g2p.py   # -> lang/jpn/port/ja_g2p_tab.c and ja_g2p_tab.h

The rules were worked out in Python, probed against words whose Japanese
loanword is not in doubt, and listened to.  The C is a translation of the
LOGIC; the tables come through here, because every table in this project that
was transcribed by hand came out with an error in it and these are the ones
whose errors would be inaudible until someone noticed a word was wrong.

Running this is also how the two stay in step: change a vowel in the Python,
re-run, and the C changes with it.
"""
import argparse
import io
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
PY = os.path.join(ROOT, 'build', 'Japanese_test')
OUT_C = os.path.join(ROOT, 'lang', 'jpn', 'port', 'ja_g2p_tab.c')
OUT_H = os.path.join(ROOT, 'lang', 'jpn', 'port', 'ja_g2p_tab.h')

HEAD = (u'/*\n'
        u' * Generated by tools/gen_ja_g2p.py from\n'
        u' * build/Japanese_test/jp_g2p.py -- do not edit.\n'
        u' *\n'
        u' * The adaptation tables: the engine\'s English phoneme alphabet,\n'
        u' * what each phoneme becomes in Japanese, and the gaps in the\n'
        u' * target inventory.  Each was probed against words whose Japanese\n'
        u' * loanword is not in doubt; the Python carries the reasoning.\n'
        u' */\n')


def clit(s):
    """A C string literal, octal so nothing runs together."""
    if s is None:
        return '0'
    return '"' + ''.join('\\%03o' % b for b in s.encode('utf-8')) + '"'


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--out-c', default=OUT_C)
    ap.add_argument('--out-h', default=OUT_H)
    args = ap.parse_args(argv)

    sys.path.insert(0, PY)
    import jp_g2p as G

    # one id per phoneme name, in a stable order
    names = sorted(set(G.NAME.values()))
    nid = dict((n, i) for i, n in enumerate(names))

    KIND_C, KIND_V, KIND_DIPH, KIND_TRIPH, KIND_YU, KIND_SPECIAL, KIND_DROP \
        = range(7)

    def kind_of(n):
        if n in G.DROP:
            return KIND_DROP
        if n == 'YU':
            return KIND_YU
        if n in G.TRIPH:
            return KIND_TRIPH
        if n in G.DIPH:
            return KIND_DIPH
        if n in G.VOWEL:
            return KIND_V
        if n in G.ONSET:
            return KIND_C
        return KIND_SPECIAL

    h = [HEAD]
    h.append(u'#ifndef JA_G2P_TAB_H\n#define JA_G2P_TAB_H\n\n')
    h.append(u'/* What a phoneme is, for the adaptation to switch on. */\n'
             u'enum {\n'
             u'    JA_P_CONS = 0,   /* a consonant, with an onset below */\n'
             u'    JA_P_VOWEL,      /* one mora nucleus, maybe long */\n'
             u'    JA_P_DIPH,       /* two morae */\n'
             u'    JA_P_TRIPH,      /* three */\n'
             u'    JA_P_YU,         /* /ju:/, which palatalises its onset */\n'
             u'    JA_P_SPECIAL,    /* NG, the syllabics, the glottal */\n'
             u'    JA_P_DROP        /* a release marker, not a sound */\n'
             u'};\n\n')
    h.append(u'#define JA_P_NONE (-1)\n')
    h.append(u'#define JA_P_COUNT %d\n\n' % len(names))
    h.append(u'/* The engine\'s one-character symbols -> a phoneme id.  -1 is\n'
             u' * "not a phoneme", which includes the stress digits and the\n'
             u' * unit markers. */\n'
             u'extern const signed char ja_g2p_sym[128];\n\n')
    h.append(u'typedef struct {\n'
             u'    const char *name;      /* the two-letter name, for '
             u'diagnostics */\n'
             u'    unsigned char kind;\n'
             u'    const char *onset;     /* JA_P_CONS: the Japanese onset */\n'
             u'    char        v[3];      /* the vowel letters it becomes */\n'
             u'    unsigned char nv;      /* how many of them */\n'
             u'    unsigned char long_;   /* a chouon follows */\n'
             u'    unsigned char shorten_unstressed;\n'
             u'} ja_g2p_phone;\n'
             u'extern const ja_g2p_phone ja_g2p_tab[JA_P_COUNT];\n\n')
    h.append(u'/* The vowel an onset takes when it has none: オ after /t d/,\n'
             u' * イ after /tʃ dʒ/, ウ otherwise. */\n'
             u'typedef struct { const char *onset; char v; } ja_g2p_pair;\n'
             u'extern const ja_g2p_pair ja_g2p_epenthetic[];\n'
             u'extern const int ja_g2p_epenthetic_n;\n'
             u'#define JA_G2P_EPENTHETIC_DEFAULT %s\n\n'
             % clit(G.EPENTHETIC_DEFAULT))
    h.append(u'/* /ju:/ palatalises rather than adding a glide, and /æ/ does\n'
             u' * after a velar: キャット, not カット. */\n'
             u'typedef struct { const char *from, *to; } ja_g2p_map;\n'
             u'extern const ja_g2p_map ja_g2p_palatal[];\n'
             u'extern const int ja_g2p_palatal_n;\n'
             u'extern const ja_g2p_map ja_g2p_ae_palatal[];\n'
             u'extern const int ja_g2p_ae_palatal_n;\n\n')
    h.append(u'/* The gaps in the target inventory, and what fills each one.\n'
             u' * Japanese has no /si zi tu du/ and the kana reader has no\n'
             u' * ウィ ウェ ウォ チェ シェ ジェ フュ; these are the substitutions,\n'
             u' * and jp_g2p.self_test is what proves the list is complete. */\n'
             u'typedef struct {\n'
             u'    const char *onset;\n'
             u'    char        v;\n'
             u'    const char *mora[2];\n'
             u'} ja_g2p_repair;\n'
             u'extern const ja_g2p_repair ja_g2p_repair_tab[];\n'
             u'extern const int ja_g2p_repair_n;\n\n')
    h.append(u'/* What geminates before it, after a real short vowel.  /d/ and\n'
             u' * /g/ do and /b/ does not -- ベッド and バッグ against クラブ --\n'
             u' * and /s/ does not either: バス, ケース. */\n'
             u'extern const char *const ja_g2p_geminate[];\n'
             u'extern const int ja_g2p_geminate_n;\n\n')
    h.append(u'#endif  /* JA_G2P_TAB_H */\n')

    c = [HEAD]
    c.append(u'#include "ja_g2p_tab.h"\n\n')
    c.append(u'const signed char ja_g2p_sym[128] = {\n')
    row = []
    for ch in range(128):
        v = G.NAME.get(chr(ch))
        row.append('%3d' % (nid[v] if v is not None else -1))
    for i in range(0, 128, 8):
        c.append(u'    %s,\n' % ', '.join(row[i:i + 8]))
    c.append(u'};\n\n')

    c.append(u'const ja_g2p_phone ja_g2p_tab[JA_P_COUNT] = {\n')
    for n in names:
        k = kind_of(n)
        onset = G.ONSET.get(n)
        vs, long_ = '', 0
        if n in G.TRIPH:
            vs = ''.join(G.TRIPH[n])
        elif n in G.DIPH:
            vs = ''.join(G.DIPH[n])
        elif n in G.VOWEL:
            v, long_ = G.VOWEL[n]
            vs = v
        sh = 1 if n in G.SHORTEN_UNSTRESSED else 0
        c.append(u'    /* %-2d */ { %-6s, %d, %-6s, { %s }, %d, %d, %d },\n'
                 % (nid[n], clit(n), k, clit(onset),
                    ', '.join("'%s'" % x for x in vs.ljust(3, '\0')
                              ).replace("'\x00'", "0"),
                    len(vs), long_, sh))
    c.append(u'};\n\n')

    c.append(u'const ja_g2p_pair ja_g2p_epenthetic[] = {\n')
    for k in sorted(G.EPENTHETIC):
        c.append(u"    { %s, '%s' },\n" % (clit(k), G.EPENTHETIC[k]))
    c.append(u'};\nconst int ja_g2p_epenthetic_n = %d;\n\n'
             % len(G.EPENTHETIC))

    for nm, d in (('palatal', G.PALATAL), ('ae_palatal', G.AE_PALATAL)):
        c.append(u'const ja_g2p_map ja_g2p_%s[] = {\n' % nm)
        for k in sorted(d):
            c.append(u'    { %s, %s },\n' % (clit(k), clit(d[k])))
        c.append(u'};\nconst int ja_g2p_%s_n = %d;\n\n' % (nm, len(d)))

    c.append(u'const ja_g2p_repair ja_g2p_repair_tab[] = {\n')
    for (ons, v) in sorted(G.REPAIR):
        ms = G.REPAIR[(ons, v)]
        c.append(u"    { %s, '%s', { %s, %s } },\n"
                 % (clit(ons), v, clit(ms[0]),
                    clit(ms[1]) if len(ms) > 1 else '0'))
    c.append(u'};\nconst int ja_g2p_repair_n = %d;\n\n' % len(G.REPAIR))

    c.append(u'const char *const ja_g2p_geminate[] = {\n')
    for g in G.GEMINATE_BEFORE:
        c.append(u'    %s,\n' % clit(g))
    c.append(u'};\nconst int ja_g2p_geminate_n = %d;\n'
             % len(G.GEMINATE_BEFORE))

    with io.open(args.out_h, 'w', encoding='utf-8', newline='\n') as fh:
        fh.write(u''.join(h))
    with io.open(args.out_c, 'w', encoding='utf-8', newline='\n') as fh:
        fh.write(u''.join(c))
    print('%s' % os.path.relpath(args.out_h, ROOT))
    print('%s' % os.path.relpath(args.out_c, ROOT))
    print('  %d phonemes, %d epenthetic, %d palatal, %d repairs, %d geminating'
          % (len(names), len(G.EPENTHETIC), len(G.PALATAL), len(G.REPAIR),
             len(G.GEMINATE_BEFORE)))
    return 0


if __name__ == '__main__':
    sys.exit(main())
