"""Generate the hook table and link-time address map for the hook build.

Usage: python tools/gen_hookmap.py <srcdir> <out_hooks.c> <out_defsyms.txt> <obj>...

Every function or global in src/ is annotated with its address in the
original DLL, in a comment directly before the declaration/definition:

    /* @0x1002c810 */
    void TV_THISCALL Engine_SetPitch(Engine *self, int32_t pitch);

    /* @0x100bf5f8 */
    extern int32_t g_object_count;

For the 32-bit hook build we look at the compiled objects:
  * an annotated symbol *defined* in the objects is decompiled: we emit a
    hook entry so the harness patches the original entry with a jmp to it;
  * an annotated symbol only *referenced* is not decompiled yet (or is
    data): we emit `--defsym SYMBOL=ADDRESS` so references resolve to the
    original code/data inside the loaded DLL.
"""
import os
import re
import subprocess
import sys

ANNOT = re.compile(r"/\*\s*@(0x[0-9a-fA-F]+)\s*(\w+)?\s*\*/")


def scan_annotations(srcdir):
    names = {}
    for root, _, files in os.walk(srcdir):
        for fn in files:
            if not fn.endswith((".c", ".h")):
                continue
            path = os.path.join(root, fn)
            text = open(path, encoding="utf-8").read()
            for m in ANNOT.finditer(text):
                addr = int(m.group(1), 16)
                rest = text[m.end():m.end() + 600]
                # declaration runs to the first ';', '{' or '='
                cut = re.search(r"[;{=]", rest)
                decl = rest[:cut.start()] if cut else rest
                decl = re.sub(r"/\*.*?\*/", " ", decl, flags=re.S)
                decl = re.sub(r"\[[^\]]*\]", "", decl)
                fm = re.search(r"([A-Za-z_]\w*)\s*\(", decl)
                if fm and not re.search(r"\(\s*\*", decl[:fm.end() + 2]):
                    name = fm.group(1)
                else:
                    ids = re.findall(r"[A-Za-z_]\w*", decl)
                    if not ids:
                        continue
                    name = ids[-1]
                if name in names and names[name] != addr:
                    sys.exit("conflicting addresses for %s: 0x%x vs 0x%x (%s)" %
                             (name, names[name], addr, path))
                names[name] = addr
    return names


def base_name(sym):
    s = sym
    if s.startswith("_"):
        s = s[1:]
    elif s.startswith("@"):
        s = s[1:]
    return s.split("@", 1)[0]


def main():
    srcdir, out_c, out_defsyms = sys.argv[1:4]
    objs = sys.argv[4:]
    names = scan_annotations(srcdir)
    defined, undefined = {}, set()
    for obj in objs:
        out = subprocess.run(["nm", obj], capture_output=True, text=True, check=True).stdout
        for line in out.splitlines():
            parts = line.split()
            if len(parts) == 2 and parts[0] == "U":
                undefined.add(parts[1])
            elif len(parts) == 3 and parts[1] in ("T", "t", "D", "d", "B", "b", "R", "r"):
                defined[parts[2]] = parts[1]
    hooks, defsyms = [], []
    for sym, kind in sorted(defined.items()):
        b = base_name(sym)
        if b in names:
            if kind not in ("T",):
                sys.exit("annotated symbol %s is defined as data in the hook build; "
                         "globals must live in the DLL for hook builds" % sym)
            hooks.append((names[b], sym, b))
    for sym in sorted(undefined):
        if sym in defined:
            continue
        b = base_name(sym)
        if b in names:
            defsyms.append((sym, names[b]))
    with open(out_c, "w", newline="\n") as fp:
        fp.write("/* Generated by tools/gen_hookmap.py -- do not edit. */\n")
        fp.write('#include "hooks.h"\n\n')
        for i, (addr, sym, b) in enumerate(hooks):
            fp.write('extern char hk_%d[] __asm__("%s");\n' % (i, sym))
        fp.write("\nconst hook_entry tv_hooks[] = {\n")
        for i, (addr, sym, b) in enumerate(hooks):
            fp.write('    {0x%08x, hk_%d, "%s"},\n' % (addr, i, b))
        fp.write("    {0, 0, 0}\n};\n")
    with open(out_defsyms, "w", newline="\n") as fp:
        for sym, addr in defsyms:
            fp.write("--defsym=%s=0x%08x\n" % (sym, addr))
    print("hooks: %d decompiled functions; %d references bound to the DLL" %
          (len(hooks), len(defsyms)))


if __name__ == "__main__":
    main()
