# -*- coding: utf-8 -*-
"""Turn the extracted Open JTalk tables into C.

    python tools/gen_ja_ojt.py     # -> ja_port/ja_ojt.c and ja_port/ja_ojt.h

`tools/gen_ja_rules.py` extracts the tables out of Open JTalk's headers into
`build/Japanese_test/ojt_tables.py`, which the Python front end reads.  This
takes that module and writes the same data as C, so the two front ends read
tables that came from one place by one route.  Running the pair of generators
is the whole provenance chain: upstream header -> Python module -> C file.

Every byte of a string is written as a three-digit octal escape with the text
in a trailing comment.  Octal escapes take at most three digits, so unlike
`\\x` they cannot swallow the character after them, and the file is then
independent of whatever execution character set the compiler was built with.
The comment is what a reader actually looks at.

Open JTalk's data is BSD 3-clause; see NOTICE.  No Open JTalk code is copied.
"""
import argparse, io, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
PY = os.path.join(ROOT, 'build', 'Japanese_test')
OUT_C = os.path.join(ROOT, 'ja_port', 'ja_ojt.c')
OUT_H = os.path.join(ROOT, 'ja_port', 'ja_ojt.h')


def clit(s):
    """A C string literal: every byte in octal, so nothing can run together."""
    return '"' + ''.join('\\%03o' % b for b in s.encode('utf-8')) + '"'


def show(s):
    """The text for a trailing comment, with the characters C would eat."""
    return s.replace('/*', '/ *').replace('*/', '* /')


def ident(name):
    out = ''.join(c if (c.isalnum() or c == '_') else '_' for c in name)
    return out.upper()


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--out-c', default=OUT_C)
    ap.add_argument('--out-h', default=OUT_H)
    args = ap.parse_args(argv)

    sys.path.insert(0, PY)
    try:
        import ojt_tables as T
    except ImportError:
        print('build/Japanese_test/ojt_tables.py is missing; run '
              'tools/gen_ja_rules.py first', file=sys.stderr)
        return 2
    if not hasattr(T, 'MORA_LIST'):
        print('ojt_tables.py has no MORA_LIST; re-run tools/gen_ja_rules.py',
              file=sys.stderr)
        return 2

    head = (u'/*\n'
            u' * Generated by tools/gen_ja_ojt.py from\n'
            u' * build/Japanese_test/ojt_tables.py -- do not edit.\n'
            u' *\n'
            u' * Open JTalk\'s rule tables, which are data and not logic.  The\n'
            u' * chain is: upstream header -> tools/gen_ja_rules.py -> the\n'
            u' * Python module both front ends were written against -> here.\n'
            u' * So the C and the Python cannot be reading different tables.\n'
            u' *\n'
            u' * Strings are octal-escaped with the text in a comment; see the\n'
            u' * generator for why.  Open JTalk is BSD 3-clause; see NOTICE.\n'
            u' */\n')

    h = [head]
    h.append(u'#ifndef JA_OJT_H\n#define JA_OJT_H\n\n')
    h.append(u'/* text2mecab_conv_list: %d substitutions applied before\n'
             u' * analysis, ASCII and halfwidth kana TO the fullwidth and\n'
             u' * composed forms naist-jdic is keyed by.  Longest source\n'
             u' * first, so the scan takes the longest match. */\n'
             u'typedef struct { const char *src, *dst; } ja_conv;\n'
             u'extern const ja_conv ja_CONV[];\n'
             u'#define ja_CONV_N %d\n\n' % (len(T.CONV), len(T.CONV)))
    h.append(u'/* njd_set_unvoiced_vowel_mora_list: the %d morae the devoicing\n'
             u' * stage knows, IN UPSTREAM\'S ORDER.  That order puts each\n'
             u' * base\'s two-character combinations before the bare one, so\n'
             u' * the first prefix match is the longest one. */\n'
             u'extern const char *const ja_MORA[];\n'
             u'#define ja_MORA_N %d\n\n'
             % (len(T.MORA_LIST), len(T.MORA_LIST)))
    h.append(u'/* njd_set_pronunciation_list: how a word the dictionary has no\n'
             u' * reading for gets one.  %d rows, first match wins. */\n'
             u'typedef struct { const char *s, *read; int morae; } ja_pron_row;\n'
             u'extern const ja_pron_row ja_PRON_LIST[];\n'
             u'#define ja_PRON_LIST_N %d\n\n'
             % (len(T.PRON_LIST), len(T.PRON_LIST)))

    c = [head]
    c.append(u'#include "ja_ojt.h"\n\n')

    # ---- CONV ------------------------------------------------------------
    c.append(u'const ja_conv ja_CONV[] = {\n')
    for a, b in T.CONV:
        c.append(u'    { %s, %s },  /* %s -> %s */\n'
                 % (clit(a), clit(b), show(a), show(b)))
    c.append(u'};\n\n')

    # ---- MORA ------------------------------------------------------------
    c.append(u'const char *const ja_MORA[] = {\n')
    for m in T.MORA_LIST:
        c.append(u'    %s,  /* %s */\n' % (clit(m), show(m)))
    c.append(u'};\n\n')

    # ---- PRON_LIST -------------------------------------------------------
    c.append(u'const ja_pron_row ja_PRON_LIST[] = {\n')
    for s, r, n in T.PRON_LIST:
        c.append(u'    { %s, %s, %d },  /* %s -> %s */\n'
                 % (clit(s), clit(r), int(n), show(s), show(r)))
    c.append(u'};\n\n')

    # ---- the digit tables ------------------------------------------------
    h.append(u'/* njd_set_digit\'s %d tables.  Eleven numeral lists, then a\n'
             u' * class list and a conversion table per counter group; the\n'
             u' * arity differs per table and the code that walks each one\n'
             u' * knows it, exactly as upstream does. */\n' % len(T.DIGIT))
    for k in sorted(T.DIGIT):
        rows = T.DIGIT[k]
        h.append(u'extern const char *const ja_dt_%s[];\n'
                 u'#define ja_dt_%s_n %d\n' % (k, k, len(rows)))
        c.append(u'const char *const ja_dt_%s[] = {\n' % k)
        for v in rows:
            c.append(u'    %s,  /* %s */\n' % (clit(v), show(v)))
        if not rows:
            c.append(u'    0  /* upstream commented every row of this one out */\n')
        c.append(u'};\n\n')
    h.append(u'\n')

    # ---- the string constants -------------------------------------------
    h.append(u'/* njd_set_digit\'s string constants.  Two are spelled\n'
             u' * NJD_SET_DITIT_ upstream, a typo the extractor takes both\n'
             u' * spellings of. */\n')
    for k in sorted(T.DIGIT_CONST):
        h.append(u'#define JA_DC_%s %s  /* %s */\n'
                 % (ident(k), clit(T.DIGIT_CONST[k]), show(T.DIGIT_CONST[k])))
    h.append(u'\n/* njd_set_accent_type\'s constants, for its digit branch --\n'
             u' * the accent of 三十, 四百, 何万. */\n')
    for k in sorted(T.ACCENT_CONST):
        h.append(u'#define JA_AC_%s %s  /* %s */\n'
                 % (ident(k), clit(T.ACCENT_CONST[k]), show(T.ACCENT_CONST[k])))

    # The part-of-speech names and the kana the other stages test.  These were
    # hand-typed on the Python side and are extracted here, so a mistyped
    # character cannot land in one front end and not the other.
    for pre, name, note in (
            ('JA_AP_', 'ACCENT_PHRASE_CONST',
             u'the part-of-speech names the eighteen accent-phrase rules test'),
            ('JA_UV_', 'UNVOICED_CONST',
             u'what the devoicing stage tests: four parts of speech, the two\n'
             u' * whole-word symbols, the devoicing mark, and the kana of the\n'
             u' * masu/desu and shi look-aheads'),
            ('JA_PR_', 'PRONUNCIATION_CONST',
             u'njd_set_pronunciation\'s own constants')):
        d = getattr(T, name)
        h.append(u'\n/* %s. */\n' % note)
        for k in sorted(d):
            if k.startswith('RULE_H'):
                continue
            h.append(u'#define %s%s %s  /* %s */\n'
                     % (pre, ident(k), clit(d[k]), show(d[k])))

    h.append(u'\n/* The three devoicing candidate classes, each with the\n'
             u' * following-mora list it devoices before.  Upstream\'s own\n'
             u' * tables: /su/ does not devoice before another s-row mora and\n'
             u' * /fu hi fi/ not before an h-row one, because that would leave\n'
             u' * two fricatives with nothing between them. */\n')
    for k in sorted(T.UNVOICED):
        h.append(u'extern const char *const ja_uv_%s[];\n'
                 u'#define ja_uv_%s_n %d\n'
                 % (k, k, len(T.UNVOICED[k])))
        c.append(u'const char *const ja_uv_%s[] = {\n' % k)
        for v in T.UNVOICED[k]:
            c.append(u'    %s,  /* %s */\n' % (clit(v), show(v)))
        c.append(u'};\n\n')

    # ---- and the few constants that are OURS -----------------------------
    #
    # Everything above is Open JTalk's data.  These four are this project's
    # own, and they are emitted from the Python that defines them rather than
    # retyped, for exactly the reason the rest of this file exists: a mistyped
    # character would land in one front end and not the other, and the
    # symptom would show up somewhere else entirely.
    import jp_njd as N
    import jp_front as F
    h.append(u'\n/* OURS, not Open JTalk\'s, emitted from the Python that\n'
             u' * defines them.  Open JTalk folds every punctuation mark into\n'
             u' * one pause symbol; this front end keeps the strong break,\n'
             u' * because its prosody grades the boundary and has nowhere\n'
             u' * later to recover the distinction.  See declared_pause in\n'
             u' * tools/ja_stage_parity.py. */\n')
    h.append(u'#define JA_OUR_PERIOD %s  /* %s */\n'
             % (clit(N.PERIOD), show(N.PERIOD)))
    for nm, seq in (('BREAK_STRONG', sorted(N.BREAK_STRONG)),
                    ('BREAK_WEAK', sorted(N.BREAK_WEAK)),
                    ('QUESTION_FORMS', sorted(N.QUESTION_FORMS))):
        h.append(u'extern const char *const ja_%s[];\n'
                 u'#define ja_%s_n %d\n' % (nm, nm, len(seq)))
        c.append(u'const char *const ja_%s[] = {\n' % nm)
        for ch in seq:
            c.append(u'    %s,  /* %s */\n' % (clit(ch), show(ch)))
        c.append(u'};\n\n')
    h.append(u'\n/* A mora the kana reader has no symbol for, spelled out\n'
             u' * rather than dropped.  Read jp_front._SPELL_OUT for what each\n'
             u' * one costs; the short version is that a bare small vowel\n'
             u' * becomes its full-size vowel and ヮ becomes /wa/, which is\n'
             u' * wrong about the consonant and right about the mora count. */\n'
             u'typedef struct { const char *kata, *romaji; } ja_spell;\n'
             u'extern const ja_spell ja_SPELL_OUT[];\n'
             u'#define ja_SPELL_OUT_N %d\n' % len(F._SPELL_OUT))
    c.append(u'const ja_spell ja_SPELL_OUT[] = {\n')
    for k in sorted(F._SPELL_OUT):
        c.append(u'    { %s, "%s" },  /* %s */\n'
                 % (clit(k), F._SPELL_OUT[k], show(k)))
    c.append(u'};\n\n')

    h.append(u'\n#endif  /* JA_OJT_H */\n')

    with io.open(args.out_h, 'w', encoding='utf-8', newline='\n') as fh:
        fh.write(u''.join(h))
    with io.open(args.out_c, 'w', encoding='utf-8', newline='\n') as fh:
        fh.write(u''.join(c))
    print('%s' % os.path.relpath(args.out_h, ROOT))
    print('%s' % os.path.relpath(args.out_c, ROOT))
    print('  %d substitutions, %d morae, %d pronunciation rows'
          % (len(T.CONV), len(T.MORA_LIST), len(T.PRON_LIST)))
    print('  %d digit tables, %d digit constants, %d accent constants'
          % (len(T.DIGIT), len(T.DIGIT_CONST), len(T.ACCENT_CONST)))
    return 0


if __name__ == '__main__':
    sys.exit(main())
